# buildspec.yml
version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 6.0
  pre_build:
    commands:
      - echo Restore dependencies...
      - dotnet restore
  build:
    commands:
      - echo Build started on `date`
      - dotnet build --configuration Release
  post_build:
    commands:
      - echo Publish artifacts...
      - dotnet publish --configuration Release --output ./build_output
artifacts:
  files:
    - '**/*'
  base-directory: 'build_output'
