# buildspec.yml
version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 6.0
  pre_build:
    commands:
      # The 'dotnet' commands need to know where your solution (.sln) or project (.csproj) file is.
      # If your code is in a subdirectory (e.g., 'src'), you must provide the path.
      - echo Restore dependencies...
      - dotnet restore Application/CloudMosaic.sln
  build:
    commands:
      - echo Build started on `date`
      - dotnet build Application/CloudMosaic.sln --configuration Release
  post_build:
    commands:
      - echo Publish artifacts...
      # The publish command should point to the specific project file (.csproj) you want to deploy.
      - dotnet publish Application/CloudMosaic.sln --configuration Release --output ./build_output
      # Copy the new platform hooks directory into the deployment package
      - cp -r .platform ./build_output/
artifacts:
  files:
    - '**/*'
  base-directory: 'build_output'

